# Generated by Django 5.2.11 on 2026-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_trip_members_only_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(),
        ),
    ]
