# Generated by Django 5.2.12 on 2026-03-11 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_meeting_start_time_alter_meeting_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
