# Generated by Django 5.2.12 on 2026-03-11 22:49

import gallery.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('album', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(storage=gallery.storage.LegacyGalleryStorage(), upload_to='')),
            ],
        ),
    ]
