# Generated by Django 5.2.12 on 2026-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryphoto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='album',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
