# Generated by Django 5.2.12 on 2026-03-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryphoto_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
