# Generated by Django 5.2.12 on 2026-03-13 22:54

import gallery.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_galleryphoto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(max_length=1024, storage=gallery.storage.LegacyGalleryStorage(), upload_to=''),
        ),
    ]
