# Generated by Django 5.2.12 on 2026-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0008_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='legacy_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
