# Generated by Django 5.2.12 on 2026-03-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0009_tripreport_legacy_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreport',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
