# Generated by Django 5.2.12 on 2026-03-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0010_alter_tripreport_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripreport',
            name='legacy_pdf',
        ),
    ]
