# Generated by Django 5.2.11 on 2026-02-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_rental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-due_date', 'member__profile__first_name', 'member__profile__last_name']},
        ),
    ]
